version: '3.3'

networks:
  app_common_network:
    external: true
  pol-common-network:
    external: true

services:
  local_adminer:
    container_name: local_adminer
    image: adminer:4.7.8
    environment:
        - 'ADMINER_DEFAULT_SERVER=${DEFAULT_DATABASE_HOST}:${DEFAULT_DATABASE_PORT}'
    restart: "no"
    ports:
      - "${ADMINER_PUBLISH_PORT}:8080"
    networks:
      - app_common_network
      - pol-common-network
    volumes:
      - ${VOLUME_PATH}:/sessions
