version: '3.3'
services:
  local_adminer:
    container_name: local_adminer
    image: adminer:4.7.8
    environment:
        - 'ADMINER_DEFAULT_SERVER=${DEFAULT_DATABASE_HOST}:${DEFAULT_DATABASE_PORT}'
    restart: "no"
    ports:
      - "${ADMINER_PUBLISH_PORT}:8080"
    networks:
      - default
    volumes:
      - ${VOLUME_PATH}:/sessions
