version: '3.3'

services:

  base-php:
    env_file:
      - .env
    image: ${APP_BASE_IMAGE_PULL_PATH}${APP_BASE_IMAGE_PHP_NAME}:${APP_BASE_IMAGE_PHP_TAG}
    build:
      context: ./
      dockerfile: ./Dockerfile
    tty: true