version: '3.3'

networks:
  app_common_network:
    external: true
  pol-common-network:
    external: true

services:
  local_mysql_3308:
    image: mysql:8.4.0
    container_name: local_mysql_3308
    ports:
      - "${PORT}:3306"
    env_file: ./.env
    volumes:
      - ${VOLUME_PATH}:/var/lib/mysql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      # - --default-authentication-plugin=mysql_native_password
      - --local-infile=1
      - --secure-file-priv=/sqls
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app_common_network
      - pol-common-network
