version: '3.3'
services:
  local_mysql_3308:
    image: mysql:8
    container_name: local_mysql_3308
    ports:
      - "${MYSQL_PORT}:3306"
    env_file: ./.env
    volumes:
      - ${VOLUME_PATH}:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
