version: '3.3'
services:
  minio:
    image: minio/minio:RELEASE.2020-12-29T23-29-29Z
    command: [ "minio", "server", "/data" ]
    restart: "no"
    env_file:
      - .env
    networks:
      - default
    volumes:
      - ${VOLUME_PATH}:/data
    ports:
      - ${MINIO_PUBLISH_PORT}:9000
